# Project-wide Gradle settings.

# JVM ???????????????? UTF-8
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# ???????????????
org.gradle.parallel=true

# ?? Gradle ????
org.gradle.caching=true

# ??????????????
org.gradle.configuration-cache=true

# ?? AndroidX
android.useAndroidX=true

# ???? R ?????????? R ?????????
android.nonTransitiveRClass=true

# Kotlin ????
kotlin.code.style=official

